export const defaultFormValues = {
  any_participant_number: false,
  schedule: [],
  repeatable: false,
  free: false,
  tags: [],
  gallery: [],
  start_time: null,
  end_time: null,
  type: undefined,
  name: '',
  image_url: '',
  description: '',
  category: undefined,
  start_date: '',
  end_date: '',
  address: '',
  city: '',
  country: '',
  city_north_east_point: undefined,
  city_south_west_point: undefined,
  location: undefined,
  desired_participants_number: NaN,
  participants_age: NaN,
  cost: null,
  currency: null
}
